In [1]:
%matplotlib inline
import pandas
import lxml

In [ ]:
drinks = pandas

In [14]:
wiki_page = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population" 
dfs = pandas.read_html(wiki_page)

In [5]:
len(dfs)

4

In [8]:
dfs[0].shape

(1, 2)

In [9]:
dfs[0]

    0                                                  1
0 NaN  This article's factual accuracy is disputed. P...

In [6]:
dfs[1].shape

(1, 2)

In [7]:
dfs[1]

    0                                                  1
0 NaN  This article possibly contains original resear...

In [10]:
dfs[2].shape

(251, 6)

In [11]:
dfs[2]

,0,1,2,3,4,5
0,Rank,Country (or dependent territory),Population,Date,% of world population,Source
1,1,China[Note 2],1378640000,"September 8, 2016",18.8%,Official population clock
2,2,India,1330730000,"September 8, 2016",18.1%,Official population clock
3,3,United States[Note 3],324429000,"September 8, 2016",4.42%,Official population clock
4,4,Indonesia,260581000,"July 1, 2016",3.55%,Official projection
5,5,Brazil,206625000,"September 8, 2016",2.81%,Official population clock
6,6,Pakistan,194196000,"September 8, 2016",2.64%,Official population clock
7,7,Nigeria,186988000,"July 1, 2016",2.55%,UN Projection
8,8,Bangladesh,161047000,"September 8, 2016",2.19%,Official population clock
9,9,Russia[Note 4],146640000,"May 1, 2016",2%,Official estimate
10,10,Mexico,128632000,"July 1, 2016",1.75%,Official projection
11,11,Japan,127000000,"August 1, 2016",1.73%,Monthly provisional estimate
12,12,Philippines,102981000,"September 8, 2016",1.4%,Official population clock
13,13,Vietnam,92700000,"July 1, 2016",1.26%,Annual official projection
14,14,Ethiopia,92206005,"July 1, 2016",1.26%,Official projection
15,15,Egypt,91545900,"September 8, 2016",1.25%,Official population clock
16,16,Democratic Republic of the Congo,82310000,"July 1, 2016",1.12%,Official estimate
17,17,Germany,82175700,"December 30, 2015",1.12%,Official estimate
18,18,Iran,79519600,"September 8, 2016",1.08%,Official population clock
19,19,Turkey,78742000,"December 31, 2015",1.07%,Annual official estimate
20,20,France[Note 5],66736000,"July 1, 2016",0.88%,Monthly official estimate
21,21,Thailand,65729098,"December 31, 2015",0.89%,Annual official estimate
22,22,United Kingdom,65110000,"July 1, 2015",0.89%,Annual official estimate
23,23,Italy,60665551,"January 1, 2016",0.83%,Official estimate
24,24,South Africa,55653654,"July 1, 2016",0.76%,Annual official estimate
25,25,Tanzania[Note 6],55155000,"July 1, 2016",0.75%,UN projection
26,26,Myanmar,54363426,"July 1, 2016",0.74%,UN projection
27,27,South Korea,50617045,"January 6, 2016",0.69%,Annual official estimate
28,28,Colombia,48827400,"September 8, 2016",0.665%,Official population clock
29,29,Kenya,47251000,"July 1, 2016",0.64%,UN projection
...,...,...,...,...,...,...
221,188,Saint Kitts and Nevis,46204,"May 15, 2011",0.00063%,2011 census result
222,189,Monaco,38400,"December 31, 2015",0.00052%,Annual official estimate
223,--,Sint Maarten (Netherlands),38247,"January 1, 2015",0.00052%,Official estimate
224,190,Liechtenstein,37623,"December 31, 2015",0.00051%,Semi annual official estimate
225,--,Saint-Martin (France),36457,"January 1, 2015",0.0005%,Annual official estimate
226,--,Gibraltar (UK),33140,"December 31, 2014",0.00045%,Annual official estimate
227,191,San Marino,33005,"December 31, 2015",0.00045%,Monthly official estimate
228,--,Turks and Caicos Islands (UK),31458,"January 25, 2012",0.00043%,2012 census result
229,--,British Virgin Islands (UK),28514,"July 1, 2013",0.00039%,Official estimate
230,--,Bonaire (Netherlands),18905,"January 1, 2015",0.00026%,Official estimate
231,--,Cook Islands,18100,"March 1, 2016",0.00025%,Official quarterly estimate
232,192,Palau,17950,"July 1, 2015",0.00024%,Annual official estimate
233,--,Anguilla (UK),13452,"May 11, 2011",0.00018%,Preliminary 2011 census result
234,--,Wallis and Futuna (France),11750,"July 1, 2015",0.00016%,Annual official estimate
235,193,Tuvalu,10640,"November 4, 2012",0.00014%,2012 census result
236,194,Nauru,10084,"October 30, 2011",0.00014%,2011 census result
237,--,Saint Barthélemy (France),9417,"January 1, 2015",0.00013%,Annual official estimate
238,--,Saint Pierre and Miquelon (France),6286,"January 1, 2015",0.000086%,Annual official estimate
239,--,Montserrat (UK),4922,"May 12, 2011",0.000067%,2011 census result
240,--,"Saint Helena, Ascension and Tristan da Cunha (UK)",4255,"February 10, 2008",0.000058%,2008 census result
241,--,Sint Eustatius (Netherlands),3877,"January 1, 2015",0.000053%,Official estimate
242,--,Falkland Islands (UK),2563,"April 15, 2012",0.000035%,2012 census result
243,--,Norfolk Island (Australia),2302,"August 9, 2011",0.000031%,2011 census result
244,--,Christmas Island (Australia),2072,"August 9, 2011",0.000028%,2011 census result
245,--,Saba (Netherlands),1811,"January 1, 2015",0.000025%,Official estimate
246,--,Niue,1470,"July 1, 2015",0.000020%,Annual official estimate
247,--,Tokelau (NZ),1411,"October 18, 2011",0.000019%,2011 census result
248,195,Vatican City,842,"January 1, 2014",0.000011%,Official estimate
249,--,Cocos (Keeling) Islands (Australia),550,"August 9, 2011",0.0000075%,2011 census result
250,--,Pitcairn Islands (UK),56,"July 1, 2014",0.00000076%,Official estimate

In [12]:
pandas.read_html?

In [15]:
dfs = pandas.read_html(wiki_page,header=0)

In [16]:
dfs[2]

,Rank,Country (or dependent territory),Population,Date,% of world population,Source
0,1,China[Note 2],1378640000,"September 8, 2016",18.8%,Official population clock
1,2,India,1330730000,"September 8, 2016",18.1%,Official population clock
2,3,United States[Note 3],324429000,"September 8, 2016",4.42%,Official population clock
3,4,Indonesia,260581000,"July 1, 2016",3.55%,Official projection
4,5,Brazil,206625000,"September 8, 2016",2.81%,Official population clock
5,6,Pakistan,194196000,"September 8, 2016",2.64%,Official population clock
6,7,Nigeria,186988000,"July 1, 2016",2.55%,UN Projection
7,8,Bangladesh,161047000,"September 8, 2016",2.19%,Official population clock
8,9,Russia[Note 4],146640000,"May 1, 2016",2%,Official estimate
9,10,Mexico,128632000,"July 1, 2016",1.75%,Official projection
10,11,Japan,127000000,"August 1, 2016",1.73%,Monthly provisional estimate
11,12,Philippines,102981000,"September 8, 2016",1.4%,Official population clock
12,13,Vietnam,92700000,"July 1, 2016",1.26%,Annual official projection
13,14,Ethiopia,92206005,"July 1, 2016",1.26%,Official projection
14,15,Egypt,91545900,"September 8, 2016",1.25%,Official population clock
15,16,Democratic Republic of the Congo,82310000,"July 1, 2016",1.12%,Official estimate
16,17,Germany,82175700,"December 30, 2015",1.12%,Official estimate
17,18,Iran,79519600,"September 8, 2016",1.08%,Official population clock
18,19,Turkey,78742000,"December 31, 2015",1.07%,Annual official estimate
19,20,France[Note 5],66736000,"July 1, 2016",0.88%,Monthly official estimate
20,21,Thailand,65729098,"December 31, 2015",0.89%,Annual official estimate
21,22,United Kingdom,65110000,"July 1, 2015",0.89%,Annual official estimate
22,23,Italy,60665551,"January 1, 2016",0.83%,Official estimate
23,24,South Africa,55653654,"July 1, 2016",0.76%,Annual official estimate
24,25,Tanzania[Note 6],55155000,"July 1, 2016",0.75%,UN projection
25,26,Myanmar,54363426,"July 1, 2016",0.74%,UN projection
26,27,South Korea,50617045,"January 6, 2016",0.69%,Annual official estimate
27,28,Colombia,48827400,"September 8, 2016",0.665%,Official population clock
28,29,Kenya,47251000,"July 1, 2016",0.64%,UN projection
29,30,Spain,46438422,"January 1, 2016",0.63%,Official estimate
...,...,...,...,...,...,...
220,188,Saint Kitts and Nevis,46204,"May 15, 2011",0.00063%,2011 census result
221,189,Monaco,38400,"December 31, 2015",0.00052%,Annual official estimate
222,--,Sint Maarten (Netherlands),38247,"January 1, 2015",0.00052%,Official estimate
223,190,Liechtenstein,37623,"December 31, 2015",0.00051%,Semi annual official estimate
224,--,Saint-Martin (France),36457,"January 1, 2015",0.0005%,Annual official estimate
225,--,Gibraltar (UK),33140,"December 31, 2014",0.00045%,Annual official estimate
226,191,San Marino,33005,"December 31, 2015",0.00045%,Monthly official estimate
227,--,Turks and Caicos Islands (UK),31458,"January 25, 2012",0.00043%,2012 census result
228,--,British Virgin Islands (UK),28514,"July 1, 2013",0.00039%,Official estimate
229,--,Bonaire (Netherlands),18905,"January 1, 2015",0.00026%,Official estimate
230,--,Cook Islands,18100,"March 1, 2016",0.00025%,Official quarterly estimate
231,192,Palau,17950,"July 1, 2015",0.00024%,Annual official estimate
232,--,Anguilla (UK),13452,"May 11, 2011",0.00018%,Preliminary 2011 census result
233,--,Wallis and Futuna (France),11750,"July 1, 2015",0.00016%,Annual official estimate
234,193,Tuvalu,10640,"November 4, 2012",0.00014%,2012 census result
235,194,Nauru,10084,"October 30, 2011",0.00014%,2011 census result
236,--,Saint Barthélemy (France),9417,"January 1, 2015",0.00013%,Annual official estimate
237,--,Saint Pierre and Miquelon (France),6286,"January 1, 2015",0.000086%,Annual official estimate
238,--,Montserrat (UK),4922,"May 12, 2011",0.000067%,2011 census result
239,--,"Saint Helena, Ascension and Tristan da Cunha (UK)",4255,"February 10, 2008",0.000058%,2008 census result
240,--,Sint Eustatius (Netherlands),3877,"January 1, 2015",0.000053%,Official estimate
241,--,Falkland Islands (UK),2563,"April 15, 2012",0.000035%,2012 census result
242,--,Norfolk Island (Australia),2302,"August 9, 2011",0.000031%,2011 census result
243,--,Christmas Island (Australia),2072,"August 9, 2011",0.000028%,2011 census result
244,--,Saba (Netherlands),1811,"January 1, 2015",0.000025%,Official estimate
245,--,Niue,1470,"July 1, 2015",0.000020%,Annual official estimate
246,--,Tokelau (NZ),1411,"October 18, 2011",0.000019%,2011 census result
247,195,Vatican City,842,"January 1, 2014",0.000011%,Official estimate
248,--,Cocos (Keeling) Islands (Australia),550,"August 9, 2011",0.0000075%,2011 census result
249,--,Pitcairn Islands (UK),56,"July 1, 2014",0.00000076%,Official estimate

In [17]:
dfs = pandas.read_html(wiki_page,header=0, index_col=0)

In [18]:
dfs[2]

,Country (or dependent territory),Population,Date,% of world population,Source
Rank,,,,,
1,China[Note 2],1378640000,"September 8, 2016",18.8%,Official population clock
2,India,1330730000,"September 8, 2016",18.1%,Official population clock
3,United States[Note 3],324429000,"September 8, 2016",4.42%,Official population clock
4,Indonesia,260581000,"July 1, 2016",3.55%,Official projection
5,Brazil,206625000,"September 8, 2016",2.81%,Official population clock
6,Pakistan,194196000,"September 8, 2016",2.64%,Official population clock
7,Nigeria,186988000,"July 1, 2016",2.55%,UN Projection
8,Bangladesh,161047000,"September 8, 2016",2.19%,Official population clock
9,Russia[Note 4],146640000,"May 1, 2016",2%,Official estimate
10,Mexico,128632000,"July 1, 2016",1.75%,Official projection
11,Japan,127000000,"August 1, 2016",1.73%,Monthly provisional estimate
12,Philippines,102981000,"September 8, 2016",1.4%,Official population clock
13,Vietnam,92700000,"July 1, 2016",1.26%,Annual official projection
14,Ethiopia,92206005,"July 1, 2016",1.26%,Official projection
15,Egypt,91545900,"September 8, 2016",1.25%,Official population clock
16,Democratic Republic of the Congo,82310000,"July 1, 2016",1.12%,Official estimate
17,Germany,82175700,"December 30, 2015",1.12%,Official estimate
18,Iran,79519600,"September 8, 2016",1.08%,Official population clock
19,Turkey,78742000,"December 31, 2015",1.07%,Annual official estimate
20,France[Note 5],66736000,"July 1, 2016",0.88%,Monthly official estimate
21,Thailand,65729098,"December 31, 2015",0.89%,Annual official estimate
22,United Kingdom,65110000,"July 1, 2015",0.89%,Annual official estimate
23,Italy,60665551,"January 1, 2016",0.83%,Official estimate
24,South Africa,55653654,"July 1, 2016",0.76%,Annual official estimate
25,Tanzania[Note 6],55155000,"July 1, 2016",0.75%,UN projection
26,Myanmar,54363426,"July 1, 2016",0.74%,UN projection
27,South Korea,50617045,"January 6, 2016",0.69%,Annual official estimate
28,Colombia,48827400,"September 8, 2016",0.665%,Official population clock
29,Kenya,47251000,"July 1, 2016",0.64%,UN projection
30,Spain,46438422,"January 1, 2016",0.63%,Official estimate
...,...,...,...,...,...
188,Saint Kitts and Nevis,46204,"May 15, 2011",0.00063%,2011 census result
189,Monaco,38400,"December 31, 2015",0.00052%,Annual official estimate
--,Sint Maarten (Netherlands),38247,"January 1, 2015",0.00052%,Official estimate
190,Liechtenstein,37623,"December 31, 2015",0.00051%,Semi annual official estimate
--,Saint-Martin (France),36457,"January 1, 2015",0.0005%,Annual official estimate
--,Gibraltar (UK),33140,"December 31, 2014",0.00045%,Annual official estimate
191,San Marino,33005,"December 31, 2015",0.00045%,Monthly official estimate
--,Turks and Caicos Islands (UK),31458,"January 25, 2012",0.00043%,2012 census result
--,British Virgin Islands (UK),28514,"July 1, 2013",0.00039%,Official estimate
--,Bonaire (Netherlands),18905,"January 1, 2015",0.00026%,Official estimate
--,Cook Islands,18100,"March 1, 2016",0.00025%,Official quarterly estimate
192,Palau,17950,"July 1, 2015",0.00024%,Annual official estimate
--,Anguilla (UK),13452,"May 11, 2011",0.00018%,Preliminary 2011 census result
--,Wallis and Futuna (France),11750,"July 1, 2015",0.00016%,Annual official estimate
193,Tuvalu,10640,"November 4, 2012",0.00014%,2012 census result
194,Nauru,10084,"October 30, 2011",0.00014%,2011 census result
--,Saint Barthélemy (France),9417,"January 1, 2015",0.00013%,Annual official estimate
--,Saint Pierre and Miquelon (France),6286,"January 1, 2015",0.000086%,Annual official estimate
--,Montserrat (UK),4922,"May 12, 2011",0.000067%,2011 census result
--,"Saint Helena, Ascension and Tristan da Cunha (UK)",4255,"February 10, 2008",0.000058%,2008 census result
--,Sint Eustatius (Netherlands),3877,"January 1, 2015",0.000053%,Official estimate
--,Falkland Islands (UK),2563,"April 15, 2012",0.000035%,2012 census result
--,Norfolk Island (Australia),2302,"August 9, 2011",0.000031%,2011 census result
--,Christmas Island (Australia),2072,"August 9, 2011",0.000028%,2011 census result
--,Saba (Netherlands),1811,"January 1, 2015",0.000025%,Official estimate
--,Niue,1470,"July 1, 2015",0.000020%,Annual official estimate
--,Tokelau (NZ),1411,"October 18, 2011",0.000019%,2011 census result
195,Vatican City,842,"January 1, 2014",0.000011%,Official estimate
--,Cocos (Keeling) Islands (Australia),550,"August 9, 2011",0.0000075%,2011 census result
--,Pitcairn Islands (UK),56,"July 1, 2014",0.00000076%,Official estimate

In [20]:
ugly_country_names = dfs[2]['Country (or dependent territory)']

In [21]:
ugly_country_names

Rank
1                                          China[Note 2]
2                                                  India
3                                  United States[Note 3]
4                                              Indonesia
5                                                 Brazil
6                                               Pakistan
7                                                Nigeria
8                                             Bangladesh
9                                         Russia[Note 4]
10                                                Mexico
11                                                 Japan
12                                           Philippines
13                                               Vietnam
14                                              Ethiopia
15                                                 Egypt
16                      Democratic Republic of the Congo
17                                               Germany
18                                                  Iran
19                                                Turkey
20                                        France[Note 5]
21                                              Thailand
22                                        United Kingdom
23                                                 Italy
24                                          South Africa
25                                      Tanzania[Note 6]
26                                               Myanmar
27                                           South Korea
28                                              Colombia
29                                                 Kenya
30                                                 Spain
                             ...
188                                Saint Kitts and Nevis
189                                               Monaco
--                            Sint Maarten (Netherlands)
190                                        Liechtenstein
--                                 Saint-Martin (France)
--                                        Gibraltar (UK)
191                                           San Marino
--                         Turks and Caicos Islands (UK)
--                           British Virgin Islands (UK)
--                                 Bonaire (Netherlands)
--                                          Cook Islands
192                                                Palau
--                                         Anguilla (UK)
--                            Wallis and Futuna (France)
193                                               Tuvalu
194                                                Nauru
--                             Saint Barthélemy (France)
--                    Saint Pierre and Miquelon (France)
--                                       Montserrat (UK)
--     Saint Helena, Ascension and Tristan da Cunha (UK)
--                          Sint Eustatius (Netherlands)
--                                 Falkland Islands (UK)
--                            Norfolk Island (Australia)
--                          Christmas Island (Australia)
--                                    Saba (Netherlands)
--                                                  Niue
--                                          Tokelau (NZ)
195                                         Vatican City
--                   Cocos (Keeling) Islands (Australia)
--                                 Pitcairn Islands (UK)
Name: Country (or dependent territory), dtype: object

In [25]:
ugly_country_names.str.extract('([A-Za-z -]*)')

/Users/tianjiaoxie/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  if __name__ == '__main__':

Rank
1                                 China
2                                 India
3                         United States
4                             Indonesia
5                                Brazil
6                              Pakistan
7                               Nigeria
8                            Bangladesh
9                                Russia
10                               Mexico
11                                Japan
12                          Philippines
13                              Vietnam
14                             Ethiopia
15                                Egypt
16     Democratic Republic of the Congo
17                              Germany
18                                 Iran
19                               Turkey
20                               France
21                             Thailand
22                       United Kingdom
23                                Italy
24                         South Africa
25                             Tanzania
26                              Myanmar
27                          South Korea
28                             Colombia
29                                Kenya
30                                Spain
                     ...
188               Saint Kitts and Nevis
189                              Monaco
--                        Sint Maarten
190                       Liechtenstein
--                        Saint-Martin
--                           Gibraltar
191                          San Marino
--            Turks and Caicos Islands
--              British Virgin Islands
--                             Bonaire
--                         Cook Islands
192                               Palau
--                            Anguilla
--                   Wallis and Futuna
193                              Tuvalu
194                               Nauru
--                          Saint Barth
--           Saint Pierre and Miquelon
--                          Montserrat
--                         Saint Helena
--                      Sint Eustatius
--                    Falkland Islands
--                      Norfolk Island
--                    Christmas Island
--                                Saba
--                                 Niue
--                             Tokelau
195                        Vatican City
--                               Cocos
--                    Pitcairn Islands
Name: Country (or dependent territory), dtype: object

In [26]:
ugly_country_names.str.extract('([^[(]*]')

/Users/tianjiaoxie/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  if __name__ == '__main__':

error: unbalanced parenthesis

In [28]:
Favourite_colours = pandas.DataFrame(data={'name':['Guarav','James','Chong','Alex'],'fav_colour': ['Green','Blue','Orange','Blue']})
Favourite_colours

  fav_colour    name
0      Green  Guarav
1       Blue   James
2     Orange   Chong
3       Blue    Alex